#!/usr/bin/env python3
import json
from pathlib import Path
import sys

from plotly.graph_objects import Figure


def main():
    if len(sys.argv) == 1:
        print('Usage: plotly-json-to-html file')
        sys.exit(0)

    input_file_path = Path(sys.argv[1])
    if not input_file_path.exists():
        print('No such file')
        sys.exit(1)

    if input_file_path.suffix != '.json':
        print('Not json file')
        sys.exit(1)

    try:
        data = json.load(input_file_path.open('r'))
    except json.JSONDecodeError:
        print('Invalid file content')
        sys.exit(1)

    save_file_path = input_file_path.parent / (input_file_path.stem + '.html')
    fig = Figure(data['data'], data['layout'])
    fig.write_html(
        str(save_file_path),
        include_plotlyjs=False,
        full_html=False,
    )


if __name__ == '__main__':
    main()
